Fix for "org.slf4j.LoggerFactory was unintentionally initialized at build time":
Error: Classes that should be initialized at run time got initialized during image building:
 org.slf4j.LoggerFactory was unintentionally initialized at build time. io.micronaut.flyway.graalvm.FlywayFeature caused initialization of this class with the following trace:
        at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:90)
        at io.micronaut.flyway.graalvm.FlywayFeature.<clinit>(FlywayFeature.java:53)